### ISSUE TITLE
Windows pip installation did not install bleson-win

### ISSUE THREAD

**Issue by carlosperate** [TheCellule/python-bleson#2]
From Windows 10 x64 running on a virtual environment with Python 3.5.2:

```
> pip install bleson
Collecting bleson
  Downloading bleson-0.0.5.tar.gz
Building wheels for collected packages: bleson
  Running setup.py bdist_wheel for bleson ... done
  Stored in directory: C:\Users\carlo\AppData\Local\pip\Cache\wheels\8d\f1\c1\f4616459bd6396743fe7b6c47914a9270076a2bbb14c59a21e
Successfully built bleson
Installing collected packages: bleson
Successfully installed bleson-0.0.5
```

```
>pip freeze
bleson==0.0.5
```

```
>python -m bleson --observer
Traceback (most recent call last):
  File "C:\python35\Lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\python35\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\carlo\Envs\hahahaha\lib\site-packages\bleson\__main__.py", line 17, in <module>
    run_observer()
  File "C:\Users\carlo\Envs\hahahaha\lib\site-packages\bleson\__main__.py", line 12, in run_observer
    with Observer(get_provider().get_adapter(), lambda advertisement_report: print(advertisement_report)):
  File "C:\Users\carlo\Envs\hahahaha\lib\site-packages\bleson\providers\__init__.py", line 21, in get_provider
    from bleson.providers.win32.win32_provider import Win32Provider
  File "C:\Users\carlo\Envs\hahahaha\lib\site-packages\bleson\providers\win32\win32_provider.py", line 2, in <module>
    from .win32_adapter import BluetoothAdapter
  File "C:\Users\carlo\Envs\hahahaha\lib\site-packages\bleson\providers\win32\win32_adapter.py", line 8, in <module>
    import blesonwin
ImportError: No module named 'blesonwin'
```

**Comment by WayneKeenan** [comment]
Looks I need to fix the deps in the setup.py. 

A temporary workaround would be to run :   

```bash
pip install bleasonwin
```

and then retry, thanks.

**Comment by WayneKeenan** [comment]
This might not be so easy, or possible, to fix for this case of installing using a single module name *and* wanting to avoid installing `sdist` packages on Win and Mac.

It centers around the lack of ability of setuptools to install wheel packages (`blesonwin` in this case)
ref: https://packaging.python.org/discussions/pip-vs-easy-install/#pip-vs-easy-install

I put in a workaround in setup.py so to install the wheels, but it has no effect when `pip install bleson` is run, only when `python3 setup.py install` is run from within the checkedout repo, that's no good for simple installation.

Unless there is some way to encode the desire to use wheels packages if available then the only other option is to document platform specific pip install instructions to specify 

`pip install bleson blesonwin` on Windows 
and 
`pip3 install bleson pyobjc` on macOS.

**Comment by WayneKeenan** [comment]
yes, I've gotten confused between 'setup.py time' and 'pip install' time. 
Although I think I've flipped the problem from being at 'pip time' to 'setup.py time', but this is better for end users.

Please let me know when you get a moment that this works for you and can be close.
Thanks
Wayne

**Comment by carlosperate** [comment]
@bennuttall has become a Python packaging expert, so maybe he's got some insight on how to achieve this successfully.

It is my understanding that doing `python setup.py install` is now deprecated, and we should be doing `pip install .`, which should support installing using wheels. I'm not sure how that affects the setup.py file exactly, or the published packaged on PyPI, but it's something I've been meaning to look into for a while.

**Comment by WayneKeenan** [comment]
thanks, ah, yes, doing a 'pip install .' should work ok now then too.  
We must forget about setup.py now.

**Comment by carlosperate** [comment]
Okay, tried `pip install bleson blesonwin`, but I might not have the right visual studio dependencies installed.

```
>pip install bleson blesonwin
Requirement already satisfied: bleson in c:\users\carlo\envs\hahahaha\lib\site-packages
Collecting blesonwin
  Using cached blesonwin-0.0.5.tar.gz
Building wheels for collected packages: blesonwin
  Running setup.py bdist_wheel for blesonwin ... error
  Complete output from command c:\users\carlo\envs\hahahaha\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\carlo\\AppData\\Local\\Temp\\pip-build-xr1e8ibb\\blesonwin\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\carlo\AppData\Local\Temp\tmp3pncjt80pip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_ext
  building 'blesonwin' extension
  creating build
  creating build\temp.win32-3.5
  creating build\temp.win32-3.5\Release
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\python35\include -IC:\python35\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\winrt" /EHsc /Tpblesonwin.cpp /Fobuild\temp.win32-3.5\Release\blesonwin.obj /std:c++latest
  cl : Command line warning D9002 : ignoring unknown option '/std:c++latest'
  blesonwin.cpp
  blesonwin.cpp(38): fatal error C1083: Cannot open include file: 'winrt/Windows.Foundation.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for blesonwin
  Running setup.py clean for blesonwin
Failed to build blesonwin
Installing collected packages: blesonwin
  Running setup.py install for blesonwin ... error
    Complete output from command c:\users\carlo\envs\hahahaha\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\carlo\\AppData\\Local\\Temp\\pip-build-xr1e8ibb\\blesonwin\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\carlo\AppData\Local\Temp\pip-49pq1fnc-record\install-record.txt --single-version-externally-managed --compile --install-headers c:\users\carlo\envs\hahahaha\include\site\python3.5\blesonwin:
    running install
    running build
    running build_ext
    building 'blesonwin' extension
    creating build
    creating build\temp.win32-3.5
    creating build\temp.win32-3.5\Release
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\python35\include -IC:\python35\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\winrt" /EHsc /Tpblesonwin.cpp /Fobuild\temp.win32-3.5\Release\blesonwin.obj /std:c++latest
    cl : Command line warning D9002 : ignoring unknown option '/std:c++latest'
    blesonwin.cpp
    blesonwin.cpp(38): fatal error C1083: Cannot open include file: 'winrt/Windows.Foundation.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\users\carlo\envs\hahahaha\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\carlo\\AppData\\Local\\Temp\\pip-build-xr1e8ibb\\blesonwin\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\carlo\AppData\Local\Temp\pip-49pq1fnc-record\install-record.txt --single-version-externally-managed --compile --install-headers c:\users\carlo\envs\hahahaha\include\site\python3.5\blesonwin" failed with error code 1 in C:\Users\carlo\AppData\Local\Temp\pip-build-xr1e8ibb\blesonwin\
```


I've got VS 2015 (14.0), but I don't have anything else VS-python related (I know for Python 2.7 and at least 3.6 you need specific version of the compiler installed when packages want to install from source via pip, MicroSoft used to distribute installables specific for Python 2.7 at least).
Unfortunately I have to run, and won't be able to test again until next week, but I'll give another go as soon as a I can.

**Comment by WayneKeenan** [comment]
Ok, because its not running in a Python 3.6 env its trying to build from source, but that wont work for two reasons:

1. I've not yet properly packaged up an 'sdist' for this, the projects `winrt` source folder isn't available.
2. VS2017 is required by the Microsoft cppwrt library that blesonwin depends upon. (That's whats in the `winrt` folder)

Steps forward:

1. I'll create a wheel for (at least) Python 3.5 which would be much easier to test by you
2. I'll look at making an sdist available for those that are able/want to build from source

thanks again for testing, much appreciated.

**Comment by WayneKeenan** [comment]
I've uploaded a Python 3.5 wheel.

```
C:\WINDOWS\system32>pip --version
pip 9.0.1 from c:\snakes\python35\lib\site-packages (python 3.5)

C:\WINDOWS\system32>pip install bleson
Collecting bleson
  Using cached bleson-0.0.6-py3-none-any.whl
Collecting blesonwin (from bleson)
  Downloading blesonwin-0.0.6-cp35-cp35m-win_amd64.whl (40kB)
    100% |################################| 40kB 327kB/s
Installing collected packages: blesonwin, bleson
Successfully installed bleson-0.0.6 blesonwin-0.0.6

C:\WINDOWS\system32>python
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import bleson
>>>

C:\WINDOWS\system32>python -m bleson --observer
2017-11-17 20:33:19,260 WARNING -         win32_adapter.py: 28 -                      off(): TODO: adatper off
2017-11-17 20:33:19,260 WARNING -         win32_adapter.py: 25 -                       on(): TODO: adatper on
2017-11-17 20:33:19,260   INFO -         win32_adapter.py: 31 -           start_scanning(): start scanning
2017-11-17 20:33:19,260   INFO -         win32_adapter.py: 37 -           start_scanning(): <function run_observer.<locals>.<lambda> at 0x0
00024F37A7A840>
228712567422298
0000024F355320D0
Advertisement(flags=0x00, name=, txpower=None uuid16s=[] uuid128s=[] rssi=-47 mfg_data=None)
228712567422298
0000024F355320D0
Advertisement(flags=0x00, name=, txpower=None uuid16s=[] uuid128s=[] rssi=-47 mfg_data=None)
27509306733705
0000024F355320D0
```

**Comment by WayneKeenan** [comment]
I've found that installing into a virtual env or `pip install bleson --user` is working for me, but on running it seg faults (on first glance, in a callback  when crossing from native->Python).

The only way I can get it to run is to install into site-packages,  but I don't yet know why.

Interested to know if it's the same for you.

**Comment by WayneKeenan** [comment]
A new version of`blesonwin` (0.0.7) has been push to PyPi which works (for me, ymmv) when installed in virtual envs and user packages.

```bash
Microsoft Windows [Version 10.0.16299.64]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\Wayne>pip install bleson --user
Collecting bleson
  Using cached bleson-0.0.9.tar.gz
Collecting blesonwin (from bleson)
  Downloading blesonwin-0.0.7-cp36-cp36m-win32.whl
Building wheels for collected packages: bleson
  Running setup.py bdist_wheel for bleson ... done
  Stored in directory: C:\Users\Wayne\AppData\Local\pip\Cache\wheels\22\20\df\9b05a828d3deec786adbadc2196ab4e6ff06ac2e5aef3441a4
Successfully built bleson
Installing collected packages: blesonwin, bleson
Successfully installed bleson-0.0.9 blesonwin-0.0.7

C:\Users\Wayne>python -m bleson --observer
2017-11-19 06:27:43,608   INFO -         win32_adapter.py: 31 -           start_scanning(): start scanning
2017-11-19 06:27:43,609   INFO -         win32_adapter.py: 37 -           start_scanning(): <function run_observer.<locals>.<lambda> at 0x05
45E420>
Advertisement(flags=0x00, name=BBC micro:bit [tegip], txpower=None uuid16s=[] uuid128s=[] rssi=-84 mfg_data=None)
Advertisement(flags=0x00, name=, txpower=None uuid16s=[] uuid128s=[] rssi=-43 mfg_data=None)
Advertisement(flags=0x00, name=, txpower=None uuid16s=[] uuid128s=[] rssi=-44 mfg_data=None)
Advertisement(flags=0x00, name=, txpower=None uuid16s=[] uuid128s=[] rssi=-43 mfg_data=None)
Advertisement(flags=0x00, name=BBC micro:bit [tegip], txpower=None uuid16s=[] uuid128s=[] rssi=-83 mfg_data=None)```

**Comment by WayneKeenan** [comment]
@carlosperate does this work for you now?

can this issue be closed?

**Comment by carlosperate** [comment]
Yes, I've just tried this in a new virtual environment with Python 3.5 and it's been fixed, thanks @WayneKeenan!

**Comment by WayneKeenan** [comment]
Great, thank you @carlosperate

**Comment by ronytesler** [comment]
> pip install bleasonwin

  ERROR: Could not find a version that satisfies the requirement bleasonwin (from versions: none)

**Comment by ronytesler** [comment]
works after installing c++ build tools.
