### ISSUE TITLE
GAP Name is UTF-8, not ASCII

### ISSUE THREAD

**Issue by tazle** [TheCellule/python-bleson#48]
This latest commit seems to break things: sometimes I get a name as bytes that isn't ascii-decodable. I'll try to find an example message that causes an exception.

In the previous version this wasn't an issue for me, because str(name) was used instead.

Traceback from when this happened:
```
Dec 26 21:11:05 pi docker[722]: Exception in thread HCISocketPoller:
Dec 26 21:11:05 pi docker[722]: Traceback (most recent call last):
Dec 26 21:11:05 pi docker[722]:   File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
Dec 26 21:11:05 pi docker[722]:     self.run()
Dec 26 21:11:05 pi docker[722]:   File "/usr/lib/python3.5/threading.py", line 862, in run
Dec 26 21:11:05 pi docker[722]:     self._target(*self._args, **self._kwargs)
Dec 26 21:11:05 pi docker[722]:   File "/src/bleson-0.0.13/bleson/providers/linux/linux_adapter.py", line 59, in _socket_poller
Dec 26 21:11:05 pi docker[722]:     self._on_data(data)
Dec 26 21:11:05 pi docker[722]:   File "/src/bleson-0.0.13/bleson/providers/linux/linux_adapter.py", line 268, in _on_data
Dec 26 21:11:05 pi docker[722]:     self._handle_meta_event(hci_event_packet)
Dec 26 21:11:05 pi docker[722]:   File "/src/bleson-0.0.13/bleson/providers/linux/linux_adapter.py", line 248, in _handle_meta_event
Dec 26 21:11:05 pi docker[722]:     advertisement = AdvertisingDataConverters.from_hcipacket(hci_packet)
Dec 26 21:11:05 pi docker[722]:   File "/src/bleson-0.0.13/bleson/core/hci/type_converters.py", line 96, in from_hcipacket
Dec 26 21:11:05 pi docker[722]:     return cls.from_hcipayload(hci_packet.data)
Dec 26 21:11:05 pi docker[722]:   File "/src/bleson-0.0.13/bleson/core/hci/type_converters.py", line 180, in from_hcipayload
Dec 26 21:11:05 pi docker[722]:     advertisement.name = payload
Dec 26 21:11:05 pi docker[722]:   File "/src/bleson-0.0.13/bleson/core/types.py", line 403, in name
Dec 26 21:11:05 pi docker[722]:     self._name = str(name,'ascii')  # TODO: is the name really UTF8 encoded according to the Core spec?
Dec 26 21:11:05 pi docker[722]: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
```

**Comment by tazle** [comment]
I don't hit this every day, and didn't catch the payload in question here. I'll see what I can do to catch it when it happens again tomorrow.

**Comment by tazle** [comment]
One issue us that this doesn't bring the process down, just the bleson HCISocketPoller thread, so systemd doesn't automatically restart the process.

**Comment by tazle** [comment]
Ok, caught the problematic name: b'v\xc3\xadvosport'

**Comment by tazle** [comment]
It seems that BT Core spec 5.0, Vol. 3, Part C, Section 12.1 specifies that GAP Device Name is a UTF-8 string. I'll create a PR of decoding it as such.
