### ISSUE TITLE
HCISocketPoller thread Exception Parsing Name

### ISSUE THREAD

**Issue by MediumFidelity** [TheCellule/python-bleson#76]
Hi, this is my first time using **python-bleson** on a Raspberry Pi to capture some BLE advertisement packets.  It's been really easy to do, but I've run into a seemingly invalid name that causes an exception that kills the `HCISocketPoller` thread.

It looks like there are two issues, the first with some goofy UFT-8 name that doesn't parse, and then an error reporting the error.

```
Exception in thread HCISocketPoller:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/bleson/core/types.py", line 404, in name
    self._name = str(name, encoding='utf-8')  # UTF-8
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 7: unexpected end of data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/bleson/providers/linux/linux_adapter.py", line 59, in _socket_poller
    self._on_data(data)
  File "/usr/local/lib/python3.5/dist-packages/bleson/providers/linux/linux_adapter.py", line 268, in _on_data
    self._handle_meta_event(hci_event_packet)
  File "/usr/local/lib/python3.5/dist-packages/bleson/providers/linux/linux_adapter.py", line 248, in _handle_meta_event
    advertisement = AdvertisingDataConverters.from_hcipacket(hci_packet)
  File "/usr/local/lib/python3.5/dist-packages/bleson/core/hci/type_converters.py", line 102, in from_hcipacket
    return cls.from_hcipayload(hci_packet.data)
  File "/usr/local/lib/python3.5/dist-packages/bleson/core/hci/type_converters.py", line 222, in from_hcipayload
    advertisement.name = payload
  File "/usr/local/lib/python3.5/dist-packages/bleson/core/types.py", line 406, in name
    log.error("Received non-UTF-8 name", payload)
NameError: name 'payload' is not defined
```

In this snippet, `payload` isn't defined.  Should it be `name`?  It came in with this PR: #49 
```
    @name.setter
    def name(self, name):
        if isinstance(name, bytearray) or isinstance(name, bytes):
            try:
                self._name = str(name, encoding='utf-8')  # UTF-8
            except UnicodeDecodeError as e:
                log.error("Received non-UTF-8 name", payload)
                raise e
        else:
            self._name = str(name)  # unit8
```

Thanks!

**Comment by MediumFidelity** [comment]
Caught a case where it happens, and tried to print `name`:

```
Message: 'Received non-UTF-8 name'
Arguments: (b'843225640\x0030A8E9\xc9\x04',)
Exception in thread HCISocketPoller:
```
