### ISSUE TITLE
Unmanaged exception

### ISSUE THREAD

**Issue by eblot** [TheCellule/python-bleson#83]
I have not looked yet at how to recover from this exception, but there is no easy way for a Bleson client to manage/mitigate it as it occurs in a working thread.

```
Exception in thread HCISocketPoller:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "python3.7/site-packages/bleson/providers/linux/linux_adapter.py", line 59, in _socket_poller
    self._on_data(data)
  File "python3.7/site-packages/bleson/providers/linux/linux_adapter.py", line 268, in _on_data
    self._handle_meta_event(hci_event_packet)
  File "python3.7/site-packages/bleson/providers/linux/linux_adapter.py", line 248, in _handle_meta_event
    advertisement = AdvertisingDataConverters.from_hcipacket(hci_packet)
  File "python3.7/site-packages/bleson/core/hci/type_converters.py", line 101, in from_hcipacket
    return cls.from_hcipayload(hci_packet.data)
  File "python3.7/site-packages/bleson/core/hci/type_converters.py", line 160, in from_hcipayload
    raise ValueError("PAyload is not divisible by 2 for UUID16")
ValueError: PAyload is not divisible by 2 for UUID16
```

(+ tiny typo in PAyload)

**Comment by eblot** [comment]
Ok, it seems it has been fixed in e4f10bea80bb3a955b7f2d6ef7003a841a975191, however there is no release with this critical fix. Would it be possible to tag/publish a new Bleson release? Thanks,.

**Comment by WayneKeenan** [comment]
yep, 1.8 just pushed to pypi.

**Comment by eblot** [comment]
Thanks a lot.
