### ISSUE TITLE
Bleson thread crashes on some malformed packet (?)

### ISSUE THREAD

**Issue by eblot** [TheCellule/python-bleson#85]
I'm using Bleson 0.1.8 on Linux (Debian 10 w/ kernel 5.12.0) with a small daemon that silently fails after a couple of days.

The issue seems to come from some kind of malformed packet (or maybe an empty one?).

Anyway, here is the trace back. I'm not sure what can be done at application level, except restarting the thread. It would be nice to discard invalid packet rather than crashing the processing thread.

Thanks.

```
Exception in thread HCISocketPoller:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/eblot/.local/lib/python3.7/site-packages/bleson/providers/linux/linux_adapter.py", line 59, in _socke
t_poller
    self._on_data(data)
  File "/home/eblot/.local/lib/python3.7/site-packages/bleson/providers/linux/linux_adapter.py", line 268, in _on_d
ata
    self._handle_meta_event(hci_event_packet)
  File "/home/eblot/.local/lib/python3.7/site-packages/bleson/providers/linux/linux_adapter.py", line 248, in _handle_meta_event
    advertisement = AdvertisingDataConverters.from_hcipacket(hci_packet)
  File "/home/eblot/.local/lib/python3.7/site-packages/bleson/core/hci/type_converters.py", line 101, in from_hcipacket
    return cls.from_hcipayload(hci_packet.data)
  File "/home/eblot/.local/lib/python3.7/site-packages/bleson/core/hci/type_converters.py", line 160, in from_hcipayload
    raise ValueError("PAyload is not divisible by 2 for UUID16")
ValueError: PAyload is not divisible by 2 for UUID16
```

**Comment by jimparis** [comment]
Are you sure you're using 0.1.8?  0.1.8 ignores all exceptions in `_on_data`, ever since https://github.com/TheCellule/python-bleson/commit/e4f10bea80bb3a955b7f2d6ef7003a841a975191
