### ISSUE TITLE
Ubuntu 20.04 --observer call fails with error

### ISSUE THREAD

**Issue by KarlBrennan** [TheCellule/python-bleson#88]
This is the first command issues after install using pip3 command.

python3 -m bleson --observer

--help works as does --url <URL> ... --beacon also crashes with same error

any light that you can shed on the cause of this issue would be much appreciated

Regards

Karl Brennan

<userAccount>@<userAccount>-ThinkPad-T590:~/PythonApps$ python3 -m bleson --observer
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/<userAccount>/.local/lib/python3.10/site-packages/bleson/__main__.py", line 28, in <module>
    run_observer()
  File "/home/<userAccount>/.local/lib/python3.10/site-packages/bleson/__main__.py", line 8, in run_observer
    with Observer(get_provider().get_adapter(), lambda advertisement_report: print(advertisement_report)):
  File "/home/<userAccount>/.local/lib/python3.10/site-packages/bleson/providers/linux/linux_provider.py", line 11, in get_adapter
    adapter.off()
  File "/home/<userAccount>/.local/lib/python3.10/site-packages/bleson/providers/linux/linux_adapter.py", line 103, in off
    self.send_cmd_value(HCIDEVDOWN, self.device_id)
  File "/home/<userAccount>/.local/lib/python3.10/site-packages/bleson/providers/linux/linux_adapter.py", line 47, in send_cmd_value
    fcntl.ioctl(self._socket.fileno(), cmd, value)
PermissionError: [Errno 1] Operation not permitted

**Comment by WayneKeenan** [comment]
Bad on the last line `PermissionError: [Errno 1] Operation not permitted` message please have a look at the `setcap` command here:  https://github.com/TheCellule/python-bleson/blob/master/docs/installing.rst#linux

**Comment by WayneKeenan** [comment]
Also, depending on what you are trying todo may I recommend either:

- https://github.com/ukBaz/python-bluezero
- https://github.com/hbldh/bleak

**Comment by KarlBrennan** [comment]
That worked a treat ... thanks
used sudo setcap cap_net_raw,cap_net_admin+eip $(eval readlink -f `which python3`)
for anyone who has a similar problem
